# Generated by Django 4.1.2 on 2024-07-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=20)),
                ('cantidad', models.CharField(max_length=3)),
                ('costo', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('precio', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=3)),
                ('cantidad', models.IntegerField(max_length=3)),
            ],
        ),
    ]
